### ISSUE TITLE
/imgs/crest@2x.png fallback always served

### ISSUE THREAD

**Issue by kaihendry** [hackerspacesg/hackerspace.sg#107]
I think it's fair to say most browsers support SVG just fine. So I don't think we need the PNG fallback which gets loaded needlessly every time.

https://github.com/hackerspacesg/hackerspace.sg/blob/master/templates/css/styles.less#L14

**Comment by kaihendry** [comment]
So is this bug fixed @Valentine ?

**Comment by Valentine** [comment]
Yes, thank you. I'll close this.
