### ISSUE TITLE
Opening Hours

### ISSUE THREAD

**Issue by chernjie** [hackerspacesg/hackerspace.sg#127]
More often than not we get this question from people out of town or new to the space.

Perhaps we should make it more obvious on the website the opening hours, i.e. 24 hours 7 days a week?

**Comment by kaihendry** [comment]
Patch on http://hackerspace.sg/faq/ ?

**Comment by robertsky** [comment]
I suggest giving visitors an smaller window, like Monday to Friday, 10AM to 10PM. The last we would want is to have visitors dropping in the middle of the night and no one is in the mood to entertain them.

**Comment by Valentine** [comment]
I think more people ask "may I visit?" than "what time are you guys open?"

But yes, I agree with @robertsky. My answer has always been a vague late morning to midnight on weekends, and early afternoon to midnight on weekends.

**Comment by robertsky** [comment]
#153 closes this.
