### ISSUE TITLE
http://cam.hackerspace.sg/lastfetched.webp gone

### ISSUE THREAD

**Issue by kaihendry** [hackerspacesg/hackerspace.sg#129]
It's now a 1024x768 https://s3-ap-southeast-1.amazonaws.com/cam.hackerspace.sg/latest.jpg

Tbh I didn't really like how we put the last camera snapshot in the background of the header. Can we think of a better design?

https://github.com/hackerspacesg/s3cam

**Comment by robertsky** [comment]
I have pushed a fix out. pending PR.

re: design. What do you propose?

**Comment by kaihendry** [comment]
Maybe the homepage looking like:

Logo  | latest.jpg
|:------------- | :------------
Upcoming events | Social media

**Comment by robertsky** [comment]
Will continue the homepage adjustments later in another issue.
