### ISSUE TITLE
https://hackerspace.sg/chat/ doesn't appear to work

### ISSUE THREAD

**Issue by kaihendry** [hackerspacesg/hackerspace.sg#139]
<img src=http://s.natalian.org/2016-05-21/1463806704_1406x1404.png>

Very old chat logs.

Maybe we are better off pointing people to https://webchat.freenode.net/ ?

**Comment by rolandturner** [comment]
We could always do the whole programmer/engineer/hacker thing and find and fix the problem...

-------- Original message --------

**Comment by rolandturner** [comment]
Kai,

I spoke to the [former] ScrollBack guys; they advise that the 
scrollback.io service is offline permanently. They also mentioned that 
although the ScrollBack code is open, it is no longer being maintained; 
they suggested that a better option for a self-hosted gateway (if we 
wished to run one) is https://thelounge.github.io/

(I should point out that the service shutdown this early was 
unintentional; their monitoring failed to notice an expired TLS 
certificate and, by the time they noticed the problem themselves months 
later, not one user of the service - including ourselves - had cared 
enough about the problem to mention it to them. I take it that they 
inferred from this that there was little point in continuing to run the 
service.)

- Roland

**Comment by notthetup** [comment]
https://gitter.im/hackerspacesg could be an alternative.

**Comment by kaihendry** [comment]
Gitter.im is effectively a closed ecosystem. I'm living free on IRC on Freenode on #hackerspace.sg with at least 15 other chaps.

I have a back channel view here: http://irc.dabase.com/

**Comment by robertsky** [comment]
necro-reviving this issue because @elfgoh asked about the /chat link recently (and in part a visitor asking as well).

using web freenode since new visitors to the irc channel doesn't seem to reference to chat history. they usually just ask if they can visit the space at X time, etc. if anyone wants history, @kaihendry's link works. otherwise, go on Slack.
