### ISSUE TITLE
Include information about Lockers a way to subscribe Lockers.

### ISSUE THREAD

**Issue by notthetup** [hackerspacesg/hackerspace.sg#40]
- Include information about Lockers subscription at Hackerspace in the Membership page (preferably with photos).

- Add Paypal subscription for big/small/tiny lockers 16/10/6 to the Membership page.

**Comment by kaihendry** [comment]
This is done IIUC https://github.com/hackerspacesg/hackerspace.sg/commit/04a033a31367bd5273a02c9b4842a4ac92d7ad70
